### ISSUE TITLE
Validator Feature - Do Not Use Exception Tags on Write Parameters

### ISSUE THREAD

**Issue by janstaelensskyline** [SkylineCommunications/Skyline.DataMiner.CICD.Validators#22]
Throw a certain error when `param/Interprete/Exceptions` is being used in combination with `param/type: write`.

See documentation: [Exceptions on Write Parameters](https://docs.dataminer.services/develop/schemadoc/Protocol/Protocol.Params.Param.Interprete.Exceptions.Exception.html#exceptions-on-write-parameters)

Example of incorrect code:

```xml
<Param id="1" setter="true">
  <Name>sdServiceKey</Name>
  <Description>SD Service Key</Description>
  <Type>write</Type>
  <Interprete>
    <RawType>numeric text</RawType>
    <Type>string</Type>
    <LengthType>next param</LengthType>
    <Exceptions>
      <Exception id="0" value="-1">
        <Value>-1</Value>
        <Display state="disabled">N/A</Display>
      </Exception>
    </Exceptions>
  </Interprete>
  <Display>
    <RTDisplay>true</RTDisplay>
  </Display>
  <Measurement>
    <Type>string</Type>
  </Measurement>
</Param>
```
Ensure any validator implementation checks for this specific misuse of `Exceptions` in write parameters to maintain the integrity and functionality of the system.

> If this feature is developed, merged, and released, the **assignee** will be granted 750 DevOps points.
> It is recommended that you add a comment here if you're starting work, or make an early Pull Request but ask us to wait on reviewing until you're done.

**Comment by EdibSU** [comment]
[PR](https://github.com/SkylineCommunications/Skyline.DataMiner.CICD.Validators/pull/40)
