### ISSUE TITLE
IndexOutOfRangeException in CheckEndlessLoop

### ISSUE THREAD

**Issue by SkylineThomasCR** [SkylineCommunications/Skyline.DataMiner.CICD.Validators#90]
> Unexpected exception in Test 'CheckEndlessLoop': System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at Skyline.DataMiner.CICD.Models.Protocol.Read.ActionTypeOptions.EquationValueClass..ctor(String option)
>    at Skyline.DataMiner.CICD.Models.Protocol.Read.ActionTypeOptions.DoublePointSignOptions(String option)
>    at Skyline.DataMiner.CICD.Models.Protocol.Read.ActionTypeOptions..ctor(String optionsAttribute)
>    at Skyline.DataMiner.CICD.Models.Protocol.Read.ActionsActionType.GetOptions()
>    at Skyline.DataMiner.CICD.Models.Protocol.Read.ActionsActionType.GetOptionsByType()
>    at Skyline.DataMiner.CICD.Validators.Protocol.Tests.Protocol.CheckEndlessLoop.CheckEndlessLoop.LoopInfo.ActionFlow(PathClass pathClass, IActionsAction action)
>    at Skyline.DataMiner.CICD.Validators.Protocol.Tests.Protocol.CheckEndlessLoop.CheckEndlessLoop.LoopInfo.CreatePath(ItemTypes currentItemType, UInt32 currentItemId, PathClass pathClass)
>    at Skyline.DataMiner.CICD.Validators.Protocol.Tests.Protocol.CheckEndlessLoop.CheckEndlessLoop.LoopInfo.TriggerFlow(PathClass pathClass, ITriggersTrigger trigger)
>    at Skyline.DataMiner.CICD.Validators.Protocol.Tests.Protocol.CheckEndlessLoop.CheckEndlessLoop.LoopInfo.CreatePath(ItemTypes currentItemType, UInt32 currentItemId, PathClass pathClass)
>    at Skyline.DataMiner.CICD.Validators.Protocol.Tests.Protocol.CheckEndlessLoop.CheckEndlessLoop.Validate(ValidatorContext context)
>    at Skyline.DataMiner.CICD.Validators.Protocol.Validator.RunValidateTest(IValidate test, ValidatorContext context, List`1 results) (line 0 col 0)

[Protocol.xml](https://github.com/user-attachments/files/17016379/Protocol.zip)
-------------------------------
DIS Info (Please do not modify)
DIS Version: 3.1.0
Visual Studio Version: 17.11.35303.130 d17.11
Windows Version: Microsoft Windows NT 10.0.22631.0
.NET Version: 4.0.30319.42000

Connected DataMiner Version: 10.4.10.0
User: Thomas Cauwelier

**Comment by PedroDebevere** [comment]
As stacktrace shows the issue resides in the Models NuGet, created a PR with a fix: [https://github.com/SkylineCommunications/Skyline.DataMiner.CICD.Models/pull/73](https://github.com/SkylineCommunications/Skyline.DataMiner.CICD.Models/pull/73)
